# Correlação Intra Classe para verificar consistência entre as medidas.

### Bibliotecas utilizadas

In [1]:
import pandas as pd
import pingouin as pg

### Lendo a base

In [2]:
caminho = r'C:\Users\saulosgil\OneDrive\Documentos\functional_tests_blinding\data\data_blinding.xlsx'
df = pd.read_excel(caminho)

df.head()

,id,idade,estado_civil,sexo,raca,renda,baixa_visao,cego,comorbidades,medicamentos,peso_kg,estatura_cm,imc,tug_1,tug_2,ts_1,ts_2
0,5.0,19.0,Solteiro,Feminino,Branco,Até 1 salário mínimo,1.0,0.0,Pre diabete,Loratadina e clenil,55.0,158.0,22.031726,8.65,6.54,15.0,18.0
1,9.0,18.0,Solteiro,Feminino,Preto,Até 1 salário mínimo,1.0,0.0,Ansiedade,Nenhum,70.0,171.0,23.938990,6.09,5.51,11.0,13.0
2,10.0,62.0,Divorciado,Masculino,Branco,1 – 2 salários mínimos,1.0,0.0,Nenhuma comorbidade,Nenhum nenhuma,85.0,180.0,26.234568,7.89,9.77,14.0,15.0
3,11.0,42.0,Solteiro,Masculino,Preto,1 – 2 salários mínimos,1.0,0.0,Nenhuma comorbidade,Não,105.0,168.0,37.202381,12.80,8.75,12.0,15.0
4,17.0,42.0,Solteiro,Masculino,Preto,Até 1 salário mínimo,1.0,0.0,Nenhuma comorbidade,Não,75.0,165.0,27.548209,10.00,8.10,10.0,12.0

## **Time Up and Go**

### Organizando os dados do TUG - wide to long

In [3]:
# Selecionar as colunas necessárias
tug_icc = df[['id', 'tug_1', 'tug_2']].copy()

# Transformar do formato wide para long
tug_long = pd.melt(
    tug_icc,
    id_vars='id',
    value_vars=['tug_1', 'tug_2'],
    var_name='day',
    value_name='score'
)

# Organizar a ordem
tug_long['day'] = tug_long['day'].map({
    'tug_1': 1,
    'tug_2': 2
})

tug_long = tug_long.sort_values(['id', 'day']).reset_index(drop=True)

tug_long.head(5)

    id  day  score
0  1.0    1   6.75
1  1.0    2   5.13
2  2.0    1   9.72
3  2.0    2   9.70
4  3.0    1   8.55

### Cálculo do ICC (modelo de dois fatores, consistência, medidas médias)

In [4]:
icc_result = pg.intraclass_corr(data=tug_long,
                                targets='id',
                                raters='day',
                                ratings='score')

# print(icc_result) - ICC3 consistência entre medidas
icc_3 = icc_result.set_index('Type').loc[['ICC(C,1)']]
icc_3

               ICC          F  df1  df2          pval         CI95
Type
ICC(C,1)  0.881069  15.816449   47   47  3.411779e-17  [0.8, 0.93]

## **Timed Stands**

### Organizando os dados do TS - wide to long

In [5]:
# Selecionar as colunas necessárias
ts_icc = df[['id', 'ts_1', 'ts_2']].copy()

# Transformar do formato wide para long
ts_long = pd.melt(
    ts_icc,
    id_vars='id',
    value_vars=['ts_1', 'ts_2'],
    var_name='day',
    value_name='score'
)

# Organizar a ordem
ts_long['day'] = ts_long['day'].map({
    'ts_1': 1,
    'ts_2': 2
})

ts_long = ts_long.sort_values(['id', 'day']).reset_index(drop=True)

ts_long.head(5)

    id  day  score
0  1.0    1   11.0
1  1.0    2   16.0
2  2.0    1   15.0
3  2.0    2   18.0
4  3.0    1   10.0

### Cálculo do ICC (modelo de dois fatores, consistência, medidas médias)

In [6]:
icc_result = pg.intraclass_corr(data=ts_long,
                                targets='id',
                                raters='day',
                                ratings='score')

# print(icc_result) - ICC3 consistência entre medidas
icc_3 = icc_result.set_index('Type').loc[['ICC(C,1)']]
icc_3

               ICC          F  df1  df2          pval          CI95
Type
ICC(C,1)  0.908799  20.929515   47   47  9.122626e-20  [0.84, 0.95]